/********************************************************************
* HLT/tgt_linuxx8664gcc/G__AliHLTTPCCAGPU.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HLT/tgt_linuxx8664gcc/G__AliHLTTPCCAGPU.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__AliHLTTPCCAGPU();
extern void G__cpp_setup_inheritanceG__AliHLTTPCCAGPU();
extern void G__cpp_setup_typetableG__AliHLTTPCCAGPU();
extern void G__cpp_setup_memvarG__AliHLTTPCCAGPU();
extern void G__cpp_setup_globalG__AliHLTTPCCAGPU();
extern void G__cpp_setup_memfuncG__AliHLTTPCCAGPU();
extern void G__cpp_setup_funcG__AliHLTTPCCAGPU();
extern void G__set_cpp_environmentG__AliHLTTPCCAGPU();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AliHLTTPCCAGPUTrackerNVCC.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_TClass;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_TBuffer;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_TMemberInspector;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_AliHLTTPCCASliceOutput;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_AliHLTTPCCASliceOutputcLcLoutputControlStruct;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_AliHLTTPCCAClusterData;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_AliHLTTPCCAParam;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_AliHLTTPCCAGPUTracker;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_AliHLTTPCCATracker;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_AliHLTLogging;
extern G__linked_taginfo G__G__AliHLTTPCCAGPULN_AliHLTTPCCAGPUTrackerNVCC;

/* STUB derived class for protected member access */
