sudo: false
matrix:
  fast_finish: true
   # Note: Workaround travis-ci/travis-ci#4681
   # Exclude default job which lacks our included environment variables.
  exclude:
    - os: linux
    - env:
  include:
    - os: linux
      env: TOOL=clang-format
      addons:
        apt:
          sources: *sources
          packages: ['clang-format-3.9']
      compiler: clang
    - os: linux
      env: TOOL=doxygen
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - cmake
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_API_TOKEN # Set in travis-ci.org dashboard
        local_dir: doc/html
        on:
          branch: dev
  allow_failures:
    # a lot of code doesn't follow clang-format yet
    - env: TOOL=clang-format
script: |
    if [[ $TOOL == "doxygen" ]]; then
      cat > CMakeLists.txt <<\EOF
      add_subdirectory(doc)
    EOF
      # This is required because of differences between doxygen and github
      # markdown syntax for code blocks. The committed code should use
      # the github flavour and we generate the doxygen one on the fly.
      git grep -l '^```[a-zA-Z]' | xargs sed -i .old -e 's|```\([a-zA-Z][a-zA-Z]*\)|\n```{.\1}\n|g;s|[.]bash|.sh|g;s|```|~~~~~~~|g'
      find . -name "*.old" -delete
      cmake .
      make doc
    elif [[ $TOOL == "clang-format" ]]; then
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        BASE_COMMIT=$(git rev-parse $TRAVIS_BRANCH)
        echo "Running clang-format-3.9 against branch $TRAVIS_BRANCH, with hash $BASE_COMMIT"
        COMMIT_FILES=$(git diff --name-only $BASE_COMMIT | grep -i -v LinkDef)
        RESULT_OUTPUT="$(git-clang-format-3.9 --commit $BASE_COMMIT --diff --binary `which clang-format-3.9` $COMMIT_FILES)"

        if [ "$RESULT_OUTPUT" == "no modified files to format" ] \
          || [ "$RESULT_OUTPUT" == "clang-format did not modify any files" ] ; then
          echo "clang-format passed."
          exit 0
        else
          echo "clang-format failed."
          echo "To reproduce it locally please run"
          echo -e "\tgit checkout $TRAVIS_BRANCH"
          echo -e "\tgit-clang-format --commit $BASE_COMMIT --diff --binary $(which clang-format)"
          echo "$RESULT_OUTPUT"
          exit 1
        fi
      fi
    fi
