sudo: false
script: |
    cat > CMakeLists.txt <<\EOF
    add_subdirectory(doc)
    EOF
    cmake .
    make doc
# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - cmake
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # Set in travis-ci.org dashboard
  local_dir: doc/html
  on:
    branch: dev
