var namespaces_dup =
[
    [ "AliTPCDcalibRes", "d9/d50/namespaceAliTPCDcalibRes.html", null ],
    [ "arrow", "d6/d7f/namespacearrow.html", "d6/d7f/namespacearrow" ],
    [ "boost", "d4/da9/namespaceboost.html", "d4/da9/namespaceboost" ],
    [ "col", "de/dca/namespacecol.html", null ],
    [ "const_str_details", "d4/df4/namespaceconst__str__details.html", null ],
    [ "coords", "d2/d91/namespacecoords.html", null ],
    [ "dptdptcorrelations", "d4/d60/namespacedptdptcorrelations.html", "d4/d60/namespacedptdptcorrelations" ],
    [ "ex2", "d4/d8f/namespaceex2.html", null ],
    [ "ex3", "d2/d51/namespaceex3.html", null ],
    [ "ex4", "d9/dc8/namespaceex4.html", null ],
    [ "extra_1", "de/dfe/namespaceextra__1.html", null ],
    [ "extra_2", "da/dfb/namespaceextra__2.html", null ],
    [ "extra_3", "d8/d4a/namespaceextra__3.html", null ],
    [ "fair", "d1/d12/namespacefair.html", "d1/d12/namespacefair" ],
    [ "gNeric", "df/d36/namespacegNeric.html", null ],
    [ "GPUCA_NAMESPACE", "db/df1/namespaceGPUCA__NAMESPACE.html", "db/df1/namespaceGPUCA__NAMESPACE" ],
    [ "GPUTPCDefinitions", "d1/dff/namespaceGPUTPCDefinitions.html", null ],
    [ "HepMC3", "dc/dd2/namespaceHepMC3.html", null ],
    [ "impl", "d8/d17/namespaceimpl.html", null ],
    [ "indices", "d2/df3/namespaceindices.html", null ],
    [ "MC", "df/dfb/namespaceMC.html", null ],
    [ "nlohmann", "d3/d9b/namespacenlohmann.html", "d3/d9b/namespacenlohmann" ],
    [ "nodes", "d1/d51/namespacenodes.html", null ],
    [ "o2", "d4/d7c/namespaceo2.html", "d4/d7c/namespaceo2" ],
    [ "painter", "d0/d06/namespacepainter.html", null ],
    [ "qConfig", "d6/dc3/namespaceqConfig.html", null ],
    [ "ROOT", "d0/d10/namespaceROOT.html", "d0/d10/namespaceROOT" ],
    [ "std", "d8/dcc/namespacestd.html", null ],
    [ "test", "df/d04/namespacetest.html", null ],
    [ "thrust", "d6/de7/namespacethrust.html", "d6/de7/namespacethrust" ],
    [ "track_utils", "d7/d4d/namespacetrack__utils.html", null ],
    [ "utils", "d6/d84/namespaceutils.html", null ]
];