// Copyright 2019-2020 CERN and copyright holders of ALICE O2.
// See https://alice-o2.web.cern.ch/copyright for details of the copyright holders.
// All rights not expressly granted are reserved.
//
// This software is distributed under the terms of the GNU General Public
// License v3 (GPL Version 3), copied verbatim in the file "COPYING".
//
// In applying this license CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

/// \file PhysicsConstants.h
/// \brief Header to collect physics constants
/// \author ruben.shahoyan@cern.ch
/// \author Vít Kučera <vit.kucera@cern.ch>, Inha University
/// \note Use the make_pdg_header.py script to generate the enums and mass declarations.

#ifndef ALICEO2_PHYSICSCONSTANTS_H_
#define ALICEO2_PHYSICSCONSTANTS_H_

#include "GPUCommonDef.h"

namespace o2::constants::physics
{
#ifdef __METAL__
// MSL has no double. The masses only ever serve as compile-time initialisers,
// and the tables built from them (PID::sMasses) are float already, so nothing
// is lost. Every other backend, device included, keeps double.
using MassType = float;
#else
using MassType = double;
#endif

// particles masses

// BEGINNING OF THE GENERATED BLOCK.
// DO NOT EDIT THIS BLOCK DIRECTLY!
// It has been generated by the make_pdg_header.py script.
// For modifications, edit the script and generate this block again.

/// \brief Declarations of named PDG codes of particles missing in ROOT PDG_t
/// \note Follow kCamelCase naming convention
/// \link https://root.cern/doc/master/TPDGCode_8h.html
enum Pdg {
  kEta = 221,
  kOmega = 223,
  kEtaPrime = 331,
  kB0 = 511,
  kB0Bar = -511,
  kBPlus = 521,
  kBCPlus = 541,
  kBS = 531,
  kBSBar = -531,
  kD0 = 421,
  kD0Bar = -421,
  kD0StarPlus = 10411,
  kD0Star0 = 10421,
  kD1Plus = 20413,
  kD10 = 20423,
  kD2StarPlus = 415,
  kD2Star0 = 425,
  kDMinus = -411,
  kDPlus = 411,
  kDS = 431,
  kDSBar = -431,
  kDSStar = 433,
  kDS1 = 10433,
  kDS1Star2700 = 30433,
  kDS1Star2860 = 40433,
  kDS2Star = 435,
  kDS3Star2860 = 437,
  kDStar = 413,
  kDStar0 = 423,
  kChiC1 = 20443,
  kJPsi = 443,
  kLambdaB0 = 5122,
  kLambdaCPlus = 4122,
  kLambdaCPlus2860 = 24124,
  kLambdaCPlus2880 = 24126,
  kLambdaCPlus2940 = 4125,
  kOmegaC0 = 4332,
  kK0Star892 = 313,
  kKPlusStar892 = 323,
  kPhi = 333,
  kSigmaC0 = 4112,
  kSigmaCPlusPlus = 4222,
  kSigmaCStar0 = 4114,
  kSigmaCStarPlusPlus = 4224,
  kX3872 = 9920443,
  kXi0 = 3322,
  kXiB0 = 5232,
  kXiCCPlusPlus = 4422,
  kXiCPlus = 4232,
  kXiC0 = 4132,
  kXiC3055Plus = 4325,
  kXiC3080Plus = 4326,
  kXiC3055_0 = 4315,
  kXiC3080_0 = 4316,
  kDeuteron = 1000010020,
  kTriton = 1000010030,
  kHelium3 = 1000020030,
  kAlpha = 1000020040,
  kLithium4 = 1000030040,
  kHyperTriton = 1010010030,
  kHyperHydrogen4 = 1010010040,
  kHyperHelium4 = 1010020040,
  kHyperHelium5 = 1010020050,
  kHyperHelium4Sigma = 1110020040,
  kLambda1520_Py = 102134,
  kK1_1270_0 = 10313,
  kK1_1270Plus = 10323,
  kCDeuteron = 2010010020
};

/// \brief Declarations of masses for additional particles
GPUglobalconstexpr() MassType MassEta = 0.547862;
GPUglobalconstexpr() MassType MassOmega = 0.78266;
GPUglobalconstexpr() MassType MassEtaPrime = 0.95778;
GPUglobalconstexpr() MassType MassB0 = 5.27966;
GPUglobalconstexpr() MassType MassB0Bar = 5.27966;
GPUglobalconstexpr() MassType MassBPlus = 5.27934;
GPUglobalconstexpr() MassType MassBCPlus = 6.27447;
GPUglobalconstexpr() MassType MassBS = 5.36692;
GPUglobalconstexpr() MassType MassBSBar = 5.36692;
GPUglobalconstexpr() MassType MassD0 = 1.86484;
GPUglobalconstexpr() MassType MassD0Bar = 1.86484;
GPUglobalconstexpr() MassType MassD0StarPlus = 2.272;
GPUglobalconstexpr() MassType MassD0Star0 = 2.343;
GPUglobalconstexpr() MassType MassD1Plus = 2.372;
GPUglobalconstexpr() MassType MassD10 = 2.412;
GPUglobalconstexpr() MassType MassD2StarPlus = 2.4601;
GPUglobalconstexpr() MassType MassD2Star0 = 2.4611;
GPUglobalconstexpr() MassType MassDMinus = 1.86966;
GPUglobalconstexpr() MassType MassDPlus = 1.86966;
GPUglobalconstexpr() MassType MassDS = 1.96835;
GPUglobalconstexpr() MassType MassDSBar = 1.96835;
GPUglobalconstexpr() MassType MassDSStar = 2.1122;
GPUglobalconstexpr() MassType MassDS1 = 2.53511;
GPUglobalconstexpr() MassType MassDS1Star2700 = 2.714;
GPUglobalconstexpr() MassType MassDS1Star2860 = 2.859;
GPUglobalconstexpr() MassType MassDS2Star = 2.5691;
GPUglobalconstexpr() MassType MassDS3Star2860 = 2.86;
GPUglobalconstexpr() MassType MassDStar = 2.01026;
GPUglobalconstexpr() MassType MassDStar0 = 2.00685;
GPUglobalconstexpr() MassType MassChiC1 = 3.51067;
GPUglobalconstexpr() MassType MassJPsi = 3.0969;
GPUglobalconstexpr() MassType MassLambdaB0 = 5.6196;
GPUglobalconstexpr() MassType MassLambdaCPlus = 2.28646;
GPUglobalconstexpr() MassType MassLambdaCPlus2860 = 2.8561;
GPUglobalconstexpr() MassType MassLambdaCPlus2880 = 2.8816;
GPUglobalconstexpr() MassType MassLambdaCPlus2940 = 2.9396;
GPUglobalconstexpr() MassType MassOmegaC0 = 2.6952;
GPUglobalconstexpr() MassType MassK0Star892 = 0.89555;
GPUglobalconstexpr() MassType MassKPlusStar892 = 0.89167;
GPUglobalconstexpr() MassType MassPhi = 1.019461;
GPUglobalconstexpr() MassType MassSigmaC0 = 2.45375;
GPUglobalconstexpr() MassType MassSigmaCPlusPlus = 2.45397;
GPUglobalconstexpr() MassType MassSigmaCStar0 = 2.51848;
GPUglobalconstexpr() MassType MassSigmaCStarPlusPlus = 2.51841;
GPUglobalconstexpr() MassType MassX3872 = 3.87165;
GPUglobalconstexpr() MassType MassXi0 = 1.31486;
GPUglobalconstexpr() MassType MassXiB0 = 5.7919;
GPUglobalconstexpr() MassType MassXiCCPlusPlus = 3.62155;
GPUglobalconstexpr() MassType MassXiCPlus = 2.46771;
GPUglobalconstexpr() MassType MassXiC0 = 2.47044;
GPUglobalconstexpr() MassType MassXiC3055Plus = 3.0559;
GPUglobalconstexpr() MassType MassXiC3080Plus = 3.0772;
GPUglobalconstexpr() MassType MassXiC3055_0 = 3.059;
GPUglobalconstexpr() MassType MassXiC3080_0 = 3.0799;
GPUglobalconstexpr() MassType MassDeuteron = 1.87561294257;
GPUglobalconstexpr() MassType MassTriton = 2.80892113298;
GPUglobalconstexpr() MassType MassHelium3 = 2.80839160743;
GPUglobalconstexpr() MassType MassAlpha = 3.7273794066;
GPUglobalconstexpr() MassType MassLithium4 = 3.7513;
GPUglobalconstexpr() MassType MassHyperTriton = 2.991134;
GPUglobalconstexpr() MassType MassHyperHydrogen4 = 3.922434;
GPUglobalconstexpr() MassType MassHyperHelium4 = 3.921728;
GPUglobalconstexpr() MassType MassHyperHelium5 = 4.839961;
GPUglobalconstexpr() MassType MassHyperHelium4Sigma = 3.995;
GPUglobalconstexpr() MassType MassLambda1520_Py = 1.5195;
GPUglobalconstexpr() MassType MassK1_1270_0 = 1.253;
GPUglobalconstexpr() MassType MassK1_1270Plus = 1.272;
GPUglobalconstexpr() MassType MassCDeuteron = 3.226;

/// \brief Declarations of masses for particles in ROOT PDG_t
GPUglobalconstexpr() MassType MassDown = 0.00467;
GPUglobalconstexpr() MassType MassDownBar = 0.00467;
GPUglobalconstexpr() MassType MassUp = 0.00216;
GPUglobalconstexpr() MassType MassUpBar = 0.00216;
GPUglobalconstexpr() MassType MassStrange = 0.0934;
GPUglobalconstexpr() MassType MassStrangeBar = 0.0934;
GPUglobalconstexpr() MassType MassCharm = 1.27;
GPUglobalconstexpr() MassType MassCharmBar = 1.27;
GPUglobalconstexpr() MassType MassBottom = 4.18;
GPUglobalconstexpr() MassType MassBottomBar = 4.18;
GPUglobalconstexpr() MassType MassTop = 172.5;
GPUglobalconstexpr() MassType MassTopBar = 172.5;
GPUglobalconstexpr() MassType MassGluon = 0.0;
GPUglobalconstexpr() MassType MassElectron = 0.000510999;
GPUglobalconstexpr() MassType MassPositron = 0.000510999;
GPUglobalconstexpr() MassType MassNuE = 0.0;
GPUglobalconstexpr() MassType MassNuEBar = 0.0;
GPUglobalconstexpr() MassType MassMuonMinus = 0.1056584;
GPUglobalconstexpr() MassType MassMuonPlus = 0.1056584;
GPUglobalconstexpr() MassType MassNuMu = 0.0;
GPUglobalconstexpr() MassType MassNuMuBar = 0.0;
GPUglobalconstexpr() MassType MassTauMinus = 1.77686;
GPUglobalconstexpr() MassType MassTauPlus = 1.77686;
GPUglobalconstexpr() MassType MassNuTau = 0.0;
GPUglobalconstexpr() MassType MassNuTauBar = 0.0;
GPUglobalconstexpr() MassType MassGamma = 0.0;
GPUglobalconstexpr() MassType MassZ0 = 91.1876;
GPUglobalconstexpr() MassType MassWPlus = 80.377;
GPUglobalconstexpr() MassType MassWMinus = 80.377;
GPUglobalconstexpr() MassType MassPi0 = 0.1349768;
GPUglobalconstexpr() MassType MassK0Long = 0.497611;
GPUglobalconstexpr() MassType MassPiPlus = 0.1395704;
GPUglobalconstexpr() MassType MassPiMinus = 0.1395704;
GPUglobalconstexpr() MassType MassProton = 0.9382721;
GPUglobalconstexpr() MassType MassProtonBar = 0.9382721;
GPUglobalconstexpr() MassType MassNeutron = 0.9395654;
GPUglobalconstexpr() MassType MassNeutronBar = 0.9395654;
GPUglobalconstexpr() MassType MassK0Short = 0.497611;
GPUglobalconstexpr() MassType MassK0 = 0.497611;
GPUglobalconstexpr() MassType MassK0Bar = 0.497611;
GPUglobalconstexpr() MassType MassKPlus = 0.493677;
GPUglobalconstexpr() MassType MassKMinus = 0.493677;
GPUglobalconstexpr() MassType MassLambda0 = 1.115683;
GPUglobalconstexpr() MassType MassLambda0Bar = 1.115683;
GPUglobalconstexpr() MassType MassLambda1520 = 1.519;
GPUglobalconstexpr() MassType MassSigmaMinus = 1.197449;
GPUglobalconstexpr() MassType MassSigmaBarPlus = 1.197449;
GPUglobalconstexpr() MassType MassSigmaPlus = 1.18937;
GPUglobalconstexpr() MassType MassSigmaBarMinus = 1.18937;
GPUglobalconstexpr() MassType MassSigma0 = 1.192642;
GPUglobalconstexpr() MassType MassSigma0Bar = 1.192642;
GPUglobalconstexpr() MassType MassXiMinus = 1.32171;
GPUglobalconstexpr() MassType MassXiPlusBar = 1.32171;
GPUglobalconstexpr() MassType MassOmegaMinus = 1.67245;
GPUglobalconstexpr() MassType MassOmegaPlusBar = 1.67245;

// END OF THE GENERATED BLOCK

// legacy names
GPUglobalconstexpr() MassType MassPhoton = MassGamma;
GPUglobalconstexpr() MassType MassMuon = MassMuonMinus;
GPUglobalconstexpr() MassType MassPionCharged = MassPiPlus;
GPUglobalconstexpr() MassType MassPionNeutral = MassPi0;
GPUglobalconstexpr() MassType MassKaonCharged = MassKPlus;
GPUglobalconstexpr() MassType MassKaonNeutral = MassK0;
GPUglobalconstexpr() MassType MassLambda = MassLambda0;
GPUglobalconstexpr() MassType MassHyperhydrog4 = MassHyperHydrogen4;
GPUglobalconstexpr() MassType MassHyperhelium4 = MassHyperHelium4;
GPUglobalconstexpr() MassType MassHyperhelium4sigma = MassHyperHelium4Sigma;

// Light speed
GPUglobalconstexpr() float LightSpeedCm2S = 299792458.e2;            // C in cm/s
GPUglobalconstexpr() float LightSpeedCm2NS = LightSpeedCm2S * 1e-9;  // C in cm/ns
GPUglobalconstexpr() float LightSpeedCm2PS = LightSpeedCm2S * 1e-12; // C in cm/ps

// Light speed inverse
GPUglobalconstexpr() float invLightSpeedCm2PS = 1. / LightSpeedCm2PS; // 1/C in ps/cm

} // namespace o2::constants::physics

#endif
