@ECHO OFF
IF '%2' == '0' CALL %1
IF '%2' == '1' CALL %1 > nul
SET VCEXECUTE=
SET BAT_SPECIAL_CHAR=0

:CHECKNEXT
IF '%3' == '' GOTO EXECUTE
IF '%3' == 'BAT_SPECIAL_EQ' GOTO SPECIAL_EQ
IF '%3' == 'BAT_SPECIAL_KOMMA' GOTO SPECIAL_KOMMA
IF '%BAT_SPECIAL_CHAR%' == '0' GOTO INSERT_SPACE
SET BAT_SPECIAL_CHAR=0
SET VCEXECUTE=%VCEXECUTE%%3
GOTO DO_SHIFT

:INSERT_SPACE
SET BAT_SPECIAL_CHAR=0
SET VCEXECUTE=%VCEXECUTE% %3
GOTO DO_SHIFT

:SPECIAL_EQ
SET BAT_SPECIAL_CHAR=1
SET VCEXECUTE=%VCEXECUTE%=
GOTO DO_SHIFT

:SPECIAL_KOMMA
SET BAT_SPECIAL_CHAR=1
SET VCEXECUTE=%VCEXECUTE%,

:DO_SHIFT
SHIFT
GOTO CHECKNEXT

:EXECUTE
%VCEXECUTE%
IF '%ERRORLEVEL%' == '0' GOTO ALLOK
ECHO ERROR
EXIT 1
:ALLOK
SET VCEXECUTE=
