#!/bin/bash

if [ $# -lt 1 ]; then
  echo usage: runMonitor <fileInfo> [pedestalFile]
fi

fileInfo=$1
pedestalFile=$2

cmd="root.exe $O2_SRC/Detectors/TPC/calibration/macro/runPedestal.C'(\"$fileInfo\")'"
echo "running: $cmd"
eval $cmd
