#!/bin/bash

if [ $# -lt 1 ]; then
  echo usage: runMonitor <fileInfo> [pedestalFile]
fi

fileInfo=$1
pedestalFile=$2

cmd="root.exe -b -q -l -n -x $O2_SRC/Detectors/TPC/calibration/macro/runPedestal.C'(\"$fileInfo\",\"$pedestalFile\")'"
echo "running: $cmd"
eval $cmd
