input = [
    { file = "in/paddedClusterFinder.json", label = "With padded digits" },
    { file = "in/packedClusterFinder.json", label = "With packed digits" }
]

type   = "bar"
out    = "out/cmpWidthPacked.pdf"
ylabel = "time [ms]"
showLegend = true
