input = [
    { file = "in/timemajor_vega20.json", label = "naive (time major) - vega20" }
    { file = "in/scratchpad4x4_vega20.json", label = "scratchpad 4x4 - vega20" }
    { file = "in/timemajor_vega10.json", label = "naive (time major) - vega10" }
    { file = "in/scratchpad4x4_vega10.json", label = "scratchpad 4x4 - vega10" }
]

type   = "bar"
out    = "out/vega10.pdf"
ylabel = "time [ms]"
showLegend = true
