macro(o2_setup_version)
  # # Set the library version in the main CMakeLists.txt
  # set(ALICEO2_MAJOR_VERSION 0) set(ALICEO2_MINOR_VERSION 0)
  # set(ALICEO2_PATCH_VERSION 0) set( ALICEO2_VERSION
  #
  # "${ALICEO2_MAJOR_VERSION}.${ALICEO2_MINOR_VERSION}.${ALICEO2_PATCH_VERSION}"
  # ) if(NOT ROOT_FOUND_VERSION OR ROOT_FOUND_VERSION LESS 59999)
  # set(FAIRROOT_LIBRARY_PROPERTIES ${FAIRROOT_LIBRARY_PROPERTIES} VERSION
  # "${ALICEO2_VERSION}" SOVERSION "${ALICEO2_MAJOR_VERSION}" SUFFIX ".so")
  # else() set(FAIRROOT_LIBRARY_PROPERTIES ${FAIRROOT_LIBRARY_PROPERTIES}
  # VERSION "${ALICEO2_VERSION}" SOVERSION
  # "${ALICEO2_MAJOR_VERSION}")
  # endif()
  #
  # generate_version_info()
endmacro()
