#!/bin/bash

usage() {
  echo "Usage:"
  echo "runPedestal <required arguments> [optional arguments]"
  echo
  echo
  echo "required arguments"
  echo "     -i, --fileInfo=     :  wildcard of input files in single quotes."
  echo "                            Can obtain the number of time bins separated by a ':'"
  echo "                            e.g. 'cru*.raw:1000' for 1000 time bins"
  echo "                            the time bin option after the ':' overwrites the --timeBins option"
  echo
  echo "optional arguments:"
  echo "    -p, --pedestalFile=  : pedestal file"
  echo "    -t, --timeBins=      : number of time bins to process (default: 1000)"
  echo "    -v, --verbosity=     : set verbosity level"
  echo "    -d, --debugLevel=    : set debug level"
  echo "    -h, --help           : show this help message"
}

usageAndExit() {
  usage
  if [[ "$0" =~ startMonitor ]]; then
    exit 0
  else
    return 0
  fi
}

# ===| default variable values |================================================
fileInfo=
pedestalFile=
timeBins=1000
verbosity=0
debugLevel=0

# ===| parse command line options |=============================================
OPTIONS=$(getopt -l "fileInfo:,pedestalFile:,timeBins:,verbosity:,debugLevel:,help" -o "i:p:t:v:d:h" -n "startMonitor" -- "$@")

if [ $? != 0 ] ; then
  usageAndExit
fi

eval set -- "$OPTIONS"

while true; do
  case "$1" in
    --) shift; break;;
    -i|--fileInfo) fileInfo=$2; shift 2;;
    -p|--pedestalFile) pedestalFile=$2; shift 2;;
    -t|--timeBins) timeBins=$2; shift 2;;
    -h|--help) usageAndExit;;
    -v|--verbosity) verbosity=$2; shift 2;;
    -d|--debugLevel) debugLevel=$2; shift 2;;
     *) echo "Internal error!" ; exit 1 ;;
   esac
done

# ===| check for required arguments |===========================================
if [[ -z "$fileInfo" ]]; then
  usageAndExit
fi

# ===| check time bin info |====================================================
if [[ $fileInfo =~ : ]]; then
  timeBins=${fileInfo#*:}
  timeBins=${timeBins%%:*}
else
  fileInfo=${fileInfo}:${timeBins}
fi

# ===| command building and execution |=========================================

cmd="root.exe $O2_SRC/Detectors/TPC/reconstruction/macro/addInclude.C $O2_SRC/Detectors/TPC/monitor/macro/RunSimpleEventDisplay.C+g'(\"$fileInfo\",\"$pedestalFile\",$timeBins,$verbosity,$debugLevel)'"
echo "running: $cmd"
eval $cmd
