#!/bin/bash
#
# Set of extra tests which may run after the full_system_test.sh
# Particularly, they use the files generated by the full_system_test.sh
#

echo "FST extra: Nothing to do for async-2022-apass4-mc-pp"
exit 0
