var namespacenlohmann_1_1detail =
[
    [ "dtoa_impl", "dc/d41/namespacenlohmann_1_1detail_1_1dtoa__impl.html", "dc/d41/namespacenlohmann_1_1detail_1_1dtoa__impl" ],
    [ "binary_reader", "d6/d30/classnlohmann_1_1detail_1_1binary__reader.html", "d6/d30/classnlohmann_1_1detail_1_1binary__reader" ],
    [ "binary_writer", "df/d1a/classnlohmann_1_1detail_1_1binary__writer.html", "df/d1a/classnlohmann_1_1detail_1_1binary__writer" ],
    [ "conjunction", "dd/dde/structnlohmann_1_1detail_1_1conjunction.html", null ],
    [ "conjunction< B1 >", "d1/d96/structnlohmann_1_1detail_1_1conjunction_3_01B1_01_4.html", null ],
    [ "conjunction< B1, Bn... >", "d5/db0/structnlohmann_1_1detail_1_1conjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ],
    [ "exception", "de/df2/classnlohmann_1_1detail_1_1exception.html", "de/df2/classnlohmann_1_1detail_1_1exception" ],
    [ "external_constructor", "d2/df4/structnlohmann_1_1detail_1_1external__constructor.html", null ],
    [ "external_constructor< value_t::array >", "d4/d91/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
    [ "external_constructor< value_t::boolean >", "d5/d36/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
    [ "external_constructor< value_t::number_float >", "d8/dff/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
    [ "external_constructor< value_t::number_integer >", "dc/dd7/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
    [ "external_constructor< value_t::number_unsigned >", "d5/df9/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
    [ "external_constructor< value_t::object >", "d7/d38/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
    [ "external_constructor< value_t::string >", "da/dac/structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
    [ "from_json_fn", "d5/d4d/structnlohmann_1_1detail_1_1from__json__fn.html", "d5/d4d/structnlohmann_1_1detail_1_1from__json__fn" ],
    [ "has_from_json", "dc/dac/structnlohmann_1_1detail_1_1has__from__json.html", null ],
    [ "has_non_default_from_json", "d7/d08/structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
    [ "has_to_json", "d9/d6c/structnlohmann_1_1detail_1_1has__to__json.html", null ],
    [ "index_sequence", "d4/d69/structnlohmann_1_1detail_1_1index__sequence.html", "d4/d69/structnlohmann_1_1detail_1_1index__sequence" ],
    [ "input_adapter", "d3/d80/classnlohmann_1_1detail_1_1input__adapter.html", "d3/d80/classnlohmann_1_1detail_1_1input__adapter" ],
    [ "input_adapter_protocol", "d8/d5f/structnlohmann_1_1detail_1_1input__adapter__protocol.html", "d8/d5f/structnlohmann_1_1detail_1_1input__adapter__protocol" ],
    [ "input_buffer_adapter", "d8/dba/classnlohmann_1_1detail_1_1input__buffer__adapter.html", "d8/dba/classnlohmann_1_1detail_1_1input__buffer__adapter" ],
    [ "input_stream_adapter", "db/df0/classnlohmann_1_1detail_1_1input__stream__adapter.html", "db/df0/classnlohmann_1_1detail_1_1input__stream__adapter" ],
    [ "internal_iterator", "d7/d10/structnlohmann_1_1detail_1_1internal__iterator.html", "d7/d10/structnlohmann_1_1detail_1_1internal__iterator" ],
    [ "invalid_iterator", "d4/d5f/classnlohmann_1_1detail_1_1invalid__iterator.html", null ],
    [ "is_basic_json", "d4/df6/structnlohmann_1_1detail_1_1is__basic__json.html", null ],
    [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "d8/d25/structnlohmann_1_1detail_1_1is__basic__json_3_01NLOHMANN__BASIC__JSON__TPL_01_4.html", null ],
    [ "is_basic_json_nested_type", "d7/da5/structnlohmann_1_1detail_1_1is__basic__json__nested__type.html", null ],
    [ "is_compatible_array_type", "d8/d94/structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ],
    [ "is_compatible_complete_type", "d8/dd4/structnlohmann_1_1detail_1_1is__compatible__complete__type.html", null ],
    [ "is_compatible_integer_type", "d1/d21/structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ],
    [ "is_compatible_integer_type_impl", "dd/d13/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
    [ "is_compatible_integer_type_impl< true, RealIntegerType, CompatibleNumberIntegerType >", "dc/d30/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01true_00_01RealIntegerType_0064332c4ada80cab3523aebd66ccc012a.html", "dc/d30/structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01true_00_01RealIntegerType_0064332c4ada80cab3523aebd66ccc012a" ],
    [ "is_compatible_object_type", "d5/dda/structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ],
    [ "is_compatible_object_type_impl", "dc/da5/structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
    [ "is_compatible_object_type_impl< true, RealType, CompatibleObjectType >", "db/d5b/structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01true_00_01RealType_00_01CompatibleObjectType_01_4.html", null ],
    [ "is_compatible_type", "d3/d71/structnlohmann_1_1detail_1_1is__compatible__type.html", null ],
    [ "is_complete_type", "d2/db3/structnlohmann_1_1detail_1_1is__complete__type.html", null ],
    [ "is_complete_type< T, decltype(void(sizeof(T)))>", "dd/dcd/structnlohmann_1_1detail_1_1is__complete__type_3_01T_00_01decltype_07void_07sizeof_07T_08_08_08_4.html", null ],
    [ "iter_impl", "d1/d7c/classnlohmann_1_1detail_1_1iter__impl.html", "d1/d7c/classnlohmann_1_1detail_1_1iter__impl" ],
    [ "iteration_proxy", "db/dda/classnlohmann_1_1detail_1_1iteration__proxy.html", "db/dda/classnlohmann_1_1detail_1_1iteration__proxy" ],
    [ "json_reverse_iterator", "de/d74/classnlohmann_1_1detail_1_1json__reverse__iterator.html", "de/d74/classnlohmann_1_1detail_1_1json__reverse__iterator" ],
    [ "lexer", "d8/d22/classnlohmann_1_1detail_1_1lexer.html", "d8/d22/classnlohmann_1_1detail_1_1lexer" ],
    [ "make_index_sequence", "d9/d0e/structnlohmann_1_1detail_1_1make__index__sequence.html", null ],
    [ "make_index_sequence< 0 >", "d9/d8f/structnlohmann_1_1detail_1_1make__index__sequence_3_010_01_4.html", null ],
    [ "make_index_sequence< 1 >", "d4/d5f/structnlohmann_1_1detail_1_1make__index__sequence_3_011_01_4.html", null ],
    [ "merge_and_renumber", "da/de9/structnlohmann_1_1detail_1_1merge__and__renumber.html", null ],
    [ "merge_and_renumber< index_sequence< I1... >, index_sequence< I2... > >", "df/d89/structnlohmann_1_1detail_1_1merge__and__renumber_3_01index__sequence_3_01I1_8_8_8_01_4_00_01inde4885d6f1d93a04f25932afbd429c4793.html", null ],
    [ "negation", "d1/d91/structnlohmann_1_1detail_1_1negation.html", null ],
    [ "other_error", "d5/d1b/classnlohmann_1_1detail_1_1other__error.html", null ],
    [ "out_of_range", "d2/d67/classnlohmann_1_1detail_1_1out__of__range.html", null ],
    [ "output_adapter", "df/d13/classnlohmann_1_1detail_1_1output__adapter.html", "df/d13/classnlohmann_1_1detail_1_1output__adapter" ],
    [ "output_adapter_protocol", "dc/d9b/structnlohmann_1_1detail_1_1output__adapter__protocol.html", "dc/d9b/structnlohmann_1_1detail_1_1output__adapter__protocol" ],
    [ "output_stream_adapter", "d8/d94/classnlohmann_1_1detail_1_1output__stream__adapter.html", "d8/d94/classnlohmann_1_1detail_1_1output__stream__adapter" ],
    [ "output_string_adapter", "d2/d39/classnlohmann_1_1detail_1_1output__string__adapter.html", "d2/d39/classnlohmann_1_1detail_1_1output__string__adapter" ],
    [ "output_vector_adapter", "d5/d66/classnlohmann_1_1detail_1_1output__vector__adapter.html", "d5/d66/classnlohmann_1_1detail_1_1output__vector__adapter" ],
    [ "parse_error", "d5/d1a/classnlohmann_1_1detail_1_1parse__error.html", "d5/d1a/classnlohmann_1_1detail_1_1parse__error" ],
    [ "parser", "df/d6b/classnlohmann_1_1detail_1_1parser.html", "df/d6b/classnlohmann_1_1detail_1_1parser" ],
    [ "primitive_iterator_t", "d2/d2c/classnlohmann_1_1detail_1_1primitive__iterator__t.html", "d2/d2c/classnlohmann_1_1detail_1_1primitive__iterator__t" ],
    [ "priority_tag", "d7/d78/structnlohmann_1_1detail_1_1priority__tag.html", null ],
    [ "priority_tag< 0 >", "d2/ddd/structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
    [ "static_const", "d1/d9b/structnlohmann_1_1detail_1_1static__const.html", null ],
    [ "to_json_fn", "d2/d7e/structnlohmann_1_1detail_1_1to__json__fn.html", "d2/d7e/structnlohmann_1_1detail_1_1to__json__fn" ],
    [ "type_error", "da/d1c/classnlohmann_1_1detail_1_1type__error.html", null ]
];