---
name: Security approval

'on':
  pull_request_review:
    types:
      - edited
      - submitted

permissions: {}

jobs:
  clean:
    name: Security approval
    uses: alisw/ali-bot/.github/workflows/pr-security-approval.yml@master
    permissions:
      pull-requests: read  # to get last commit for PR
      statuses: write      # for set-github-status
