name: pragma-once checker

on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Run pragma check
      id: pragma_check
      run: |
        git --no-pager grep -l '#pragma once' -- '*.h' && exit 1 || exit 0
